name: "Topic Management"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 
env:
 # verbosity setting for Terraform logs
 TF_LOG: INFO
 TF_VAR_confluent_cloud_api_key: ${{ secrets.CCLOUD_API_KEY }}
 TF_VAR_confluent_cloud_api_secret: ${{ secrets.CCLOUD_API_SECRET }}
jobs:
 terraform:
   name: "Terraform Infrastructure Change Management"
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
       # We keep Terraform files in the terraform directory.
       working-directory: ./
   steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2
     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: 1.3.7
     - name: Terraform init
       id: init
       run: terraform init
     - name: Terraform format
       id: fmt
       run: terraform fmt -check
     - name: Terraform validate
       id: validate
       run: terraform validate
     - name: Terraform plan
       id: plan
       if: github.event_name == 'pull_request'
       run: terraform plan -no-color -var-file="env/topics.tfvars" -input=false
       continue-on-error: true
     - name: Terraform Plan Status
       if: steps.plan.outcome == 'failure'
       run: exit 1
     - name: Terraform Apply
       if: github.ref == 'refs/heads/main' && github.event_name == 'push'
       run: terraform apply -var-file="env/topics.tfvars" -auto-approve -input=false